[package]
name = "radix"
version = "0.6.0"
authors = ["Joey EzechiÃ«ls <joey.ezechiels@gmail.com>"]
description = "Convert any {u8, u16, u32, u64, u128, usize} to another radix"
license = "MIT"
edition = "2018"
repository = "http://github.com/jjpe/radix"

[dependencies]
